### ISSUE TITLE
Build failing during graph generation

### ISSUE THREAD

**Issue by Brand07** [sockheadrps/PyProfileDataGen#13]
Hi and thanks for your tool. I'm looking forward to using it, but It seems to fail for me during the generation of the graphs.

I've set this up multiple times following your guide, generating new keys, setting up the readme, config.ini, and actions to ensure I'm not doing anything wrong, but this is what I get when the build fails:

`Construct counts graph generated successfully.
Lines of code and total commits scatter plot generated successfully.
Lines of code line chart generated successfully.
Top libraries graph generated successfully.
Exception in callback Browser.run_read_loop.<locals>.check_error(<Task finishe...ition 680'}})>) at /opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/choreographer/browser.py:663
handle: <Handle Browser.run_read_loop.<locals>.check_error(<Task finishe...ition 680'}})>) at /opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/choreographer/browser.py:663>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/choreographer/browser.py", line 670, in check_error
    raise e
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/choreographer/browser.py", line 680, in read_loop
    raise DevtoolsProtocolError(response)
choreographer.protocol.DevtoolsProtocolError: {'error': {'code': -32700, 'message': 'JSON: invalid token at position 680'}}
Traceback (most recent call last):
  File "/home/runner/work/Brand07/Brand07/Generator/utils/graphing/commit_heatmap.py", line 60, in <module>
    fig.write_image("DataVisuals/commit_heatmap.png", width=1200, height=800)
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/plotly/basedatatypes.py", line 3841, in write_image
    return pio.write_image(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/plotly/io/_kaleido.py", line 266, in write_image
    img_data = to_image(
               ^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/plotly/io/_kaleido.py", line [14](https://github.com/Brand07/Brand07/actions/runs/11897227602/job/33150982306#step:10:15)3, in to_image
    img_bytes = scope.transform(
                ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/kaleido/scopes/plotly.py", line 233, in transform
    img = kaleido.to_image_block(spec, Path(self._tempfile.name).absolute(), self._topojson, self._mapbox_access_token, debug=debug, tmp_path=self._tmp_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/kaleido/__init__.py", line 43, in to_image_block
    return asyncio.run(to_image(spec, f, topojson, mapbox_token, debug=debug, tmp_path=tmp_path))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/asyncio/runners.py", line 1[18](https://github.com/Brand07/Brand07/actions/runs/11897227602/job/33150982306#step:10:19), in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/kaleido/__init__.py", line 129, in to_image
    response = await tab.send_command("Runtime.callFunctionOn", params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
choreographer.browser.BrowserClosedError: Command not completed because browser closed.
Error: Process completed with exit code 1.`

**Comment by Brand07** [comment]
Update: Seems to have resolved itself. I let it sit for a day or two and the build runs smoothly. Thanks!

**Comment by sockheadrps** [comment]
> Update: Seems to have resolved itself. I let it sit for a day or two and the build runs smoothly. Thanks!

Oh crap dude Im sorry I hadnt seen this issue, really sorry about that!
Thats interesting, Ive never seen it fail in that way before, its not immediately clear  what went wrong from the logs.
> Command not completed because browser closed. Error: Process completed with exit code 1.

Thats one I havnt seen before for sure, it looks like maybe it had something to do with githubs servers at the time, its hard to say. Let me know if it ever happens again but I usually run it once or twice a week and never seen that one. I also have github premium or whatever though so idk if that might have an effect on how reliable the servers that run the actions are for me.


Thanks for opening the issue, I always appreciate feedback, even if its just stuff I need to fix!

**Comment by sockheadrps** [comment]
Well. Haha. Looks like I do infact have some things to fix, I just went to your profile to check out your stats and I see some things that arent quite right, so thanks for opening up an issue!

**Comment by Brand07** [comment]
Not a problem! I appreciate the tool!
